@startuml OnReadComplete
InputHandler -> MqttClient : OnComplete|OnReadError
MqttClient -> OutputHandler : Close(StopCurrentWrite/StopWriteLoop)
OutputHandler -> PipeWriter : Complete
MqttClient -> IMqttChannel : Close
@enduml
