@startuml
package IChannel {
    interface NetworkStream
}
package IncomingMessageHandler {
    queue InputPipe
    control ReadLoopAsync
    entity Reflexes
}

package OutgoingMessageHandler {
    control ChannelLoop
    queue PipeWriterOutput
    queue OutPipeline [
        Channel<OutgoingMessage> OutPipeline
    ]

    queue ReflexOutPipeline [
        Channel<OutgoingMessage> ReflexOutPipeline
    ]

    entity OutgoinPacket [
        OutgoinPacket.Write(PipeWriter)
    ]
}

package MqttClient {
    entity MqttEvents
    entity MqttActions
}

MqttActions --> OutPipeline
NetworkStream --> InputPipe
PipeWriterOutput --> NetworkStream

OutgoinPacket --> PipeWriterOutput
OutPipeline --> ChannelLoop : pull
ReflexOutPipeline --> ChannelLoop : pull in priority
ChannelLoop --> OutgoinPacket


ReadLoopAsync <-- InputPipe
Reflexes <-- ReadLoopAsync
MqttEvents <-- Reflexes : IncomingMessage
Reflexes --> ReflexOutPipeline
cloud UserProcess
UserProcess <-- MqttEvents
cloud UserAction
UserAction --> MqttActions
@enduml