using System.Threading.Tasks;

namespace CK.MQTT.Stores
{
    /// <summary>
    /// Store packet identifier not generated by this mqtt instance.
    /// </summary>
    /// <remarks>
    /// We don't use a <see cref="IdStore"/> for incoming packet identified because they are not corellated to the locally generated packet identifier.
    /// </remarks>
    public interface IIncomingPacketStore
    {
        ValueTask StoreId( IInputLogger? m, int id );

        ValueTask RemoveId( IInputLogger? m, int id );

        bool Empty { get; }

        ValueTask ResetAsync();
    }
}
