<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Common\MQTT.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="27.1.0-mike.0.ci.3" />
    <PackageReference Include="CK.PerfectEvent" Version="29.0.0-mike.0.ci.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.MQTT.LowLevelClient\CK.MQTT.LowLevelClient.csproj" />
  </ItemGroup>
</Project>