<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Common\MQTT.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Concrete implementations of CK.MQTT.Abstractions.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageReference Include="Nerdbank.Streams" Version="2.14.354" />
  </ItemGroup>
</Project>