name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: InferSharp
        uses: microsoft/infersharpaction@v0.2
        id: runinfersharp
        with:
          binary-path: 'CK.MQTT.Client\bin\Release\netcoreapp3.1'
      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }
